export interface DefaultPrices {
    nac: StatesModel | number,
    mat: number,
    def: number,
    div: number,
    cot: number,
    der: number,
    nss: number,
    rfc: number,
    inh: number,
    ret: number,
    sus: number,
    ecu: number,
    reset: number,
    arfc: number,
    dnac: number,
    curp: number,
    cfe: number,
}

interface StatesModel {
    bcn: number,
    yuca: number,
    bcs: number,
    vera: number,
    coah: number,
    mich: number,
    tlax: number,
    dura: number,
    agua: number,
    chia: number,
    hida: number,
    pueb: number,
    quer: number,
    chih: number,
    oaxa: number,
    sono: number,
    slp: number,
    sina: number,
    guer: number,
    zaca: number,
    tama: number,
    more: number,
    taba: number,
    guan: number,
    coli: number,
    jali: number, 
    cdmx: number,
    naya: number,
    camp: number,
    nl: number,
    mex: number,
    qroo: number,
    ext: number,
}